-- First, remove the table if it exists
drop table if exists bookmarks;

-- Create the table anew
create table bookmarks (
  id INTEGER primary key generated by default as identity,
  bookmark_name TEXT NOT NULL,
  bookmark_description TEXT NOT NULL,
  bookmark_url TEXT NOT NULL,
  bookmark_rating INTEGER 
);

-- insert some test data
-- Using a multi-row insert statement here
insert into bookmarks (bookmark_name, bookmark_description, bookmark_url, bookmark_rating)
values
  ('Thinkful','Think outside the classroom', 'https://www.thinkful.com', 5),
  ('Googs','The answer to everything.', 'https://www.google.com', 5),
  ('Google Machine','Search search search', 'https://www.google.com', 2),
  ('Yahoo','Yahoo thing', 'https://www.yahoo.com', 2),
  ('Pinterest','Pin the ideas...', 'https://www.pinterest.com', 3),
  ('Portfolio','The stuff I make', 'https://www.rachylquan.com', 3),
  ('Instagram','Picture memories', 'https://www.instagram.com', 4),
  ('Facebook','A book of faces', 'https://www.facebook.com', 2),
  ('Bing','A terrible search engine', 'https://www.bing.com', 1),
  ('Gmail','The one with the email', 'https://www.gmail.com', 4);


  -- Design a table to store the bookmarks. For each attribute of a bookmark that you can think of, identify the data type, size, whether it can be null, if its a primary key and if a default value makes sense.